# Generated by Django 3.1.2 on 2020-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='income',
            field=models.FloatField(blank=True, null=True, verbose_name='monthly income'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='savings',
            field=models.FloatField(blank=True, null=True, verbose_name='monthly savings'),
        ),
    ]
