# Generated by Django 3.1.2 on 2020-10-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20201025_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='income',
            field=models.FloatField(blank=True, default=0.0, verbose_name='monthly income'),
        ),
    ]
